export {Signup} from './components/Signup'
export {Login} from './components/Login'
export {OTPVerification} from './components/OTPVerification'
export {Timer} from './components/Timer'
export {SubmitModal} from './components/SubmitModal'